/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'card-bg': 'var(--card-bg)',
        'accent': 'var(--accent)',
        'text-primary': 'var(--text-primary)',
        'text-muted': 'var(--text-muted)',
        'border-color': 'var(--border-color)',
        'glass-border': 'var(--glass-border)',
        'header-bg': 'var(--header-bg)',
        'nav-bg': 'var(--nav-bg)',
        'modal-overlay-bg': 'var(--modal-overlay-bg)',
        'hover-bg': 'var(--hover-bg)',
        'pl-purple': 'var(--pl-purple)',
        'pl-green': 'var(--pl-green)',
        'pl-blue': 'var(--pl-blue)',
        'pl-pink': 'var(--pl-pink)',
        'ga-bg': 'var(--ga-bg)',
        'ga-text': 'var(--ga-text)',
        'br-navy': 'var(--br-navy)',
        'br-green': 'var(--br-green)',
        'br-yellow': 'var(--br-yellow)',
        'br-blue': 'var(--br-blue)',
        'lfu-bg': 'var(--lfu-bg)',
        'lfu-text': 'var(--lfu-text)',
        'lfu-yellow': 'var(--lfu-yellow)',
        'lfu-blue': 'var(--lfu-blue)',
        'lfu-green': 'var(--lfu-green)',
        'lfu-white': 'var(--lfu-white)',
        'card-yellow': 'var(--card-yellow)',
        'card-red': 'var(--card-red)',
        background: '#0a0f18',
        surface: '#111827',
        primary: '#3b82f6',
        text: '#ffffff',
        muted: '#9ca3af',
      }
    },
  },
  plugins: [],
}
